### ISSUE TITLE
Most useful tips for epidemiological coders

### ISSUE THREAD

**Issue by ben18785** [OxfordRSE/How-to-write-better-research-code-NTD-Technical-Meeting-2021#1]
I've been going through the various links (thanks @tlestang!) and, to my mind, the following is an ordering representing the prevalence of various code smells in epidemiological code. Note, this partly reflects that most epidemiological people code in R (there are people that also code in C++ but I don't know the language as well) and don't tend to use classes.

1. Long parameter lists (I liked the refactoring guru heuristic here ">3/4 parameters?")
2. Long methods
3. Highly nested if/else loops (Jenny Bryan's presentation had a good example of this)
4. Comments within methods
5. Abstract or unhelpful variable or function names

What are your thoughts @tlestang ? Any clangers I've missed off? I don't think we'll want to go into the detail of too many.

**Comment by tlestang** [comment]
Thansk for that, I think it looks good, these smells don't come as a surprise. One thing that is missing imo is duplicated code. I don't remember if this is among the list of smells but definitely something common. It would be worth mentioning why this can be a problem and how to avoid it.

**Comment by tlestang** [comment]
So we could group them into topics now:

- Long stuff (bloaters): (1) and (2)
- Complex stuff: (3) We can briefly mention more conceptual topics like cyclomatic complexity for the keen people in the audience.
- Badly named stuff: Non-descriptive names (variables and functions), Unnecessary comments (because sometimes it comes down to better names).

I realise as I'm writing this that we could take 2 points of views: either _tips to write better code_ or _things that make code bad_. I suggest we stick to the former because we want to convey the message that 

> There is an ensemble of approaches and rules of thumb which can really positively impact code quality. They are not very well known in the community, but well within any epidemiologist's reach.

instead of 

> There is an ensemble of basic things that can make software bad, and most of you do them, therefore your are bad programmers and irresponsible scientists.

I'm pushing things a bit here but you get the idea

**Comment by iamleeg** [comment]
Just an observation that [fancy complexity metrics are all linearly correlated with lines of code](https://arxiv.org/abs/1408.4523), so "look for a simpler, shorter solution" is presumably linearly correlated with "reduce fancy metric score" and will be easier to understand :)

**Comment by ben18785** [comment]
Yep, good point @tlestang re: duplicated code. I like your grouping. My thoughts would be to, as you suggest, put things in a positive light (in my experience, positive suggestions -- "this would make code more readable" -- are received better than negative ones -- "this is really badly written code").

I was wondering, since most of the audience will use R, could we do something like have a series of mini breakouts throughout the talk for people to discuss issues with some code snippets we present them with? These snippets could be designed to tick off each of the boxes above. If I were in the audience and it was late in the day (as it will be when we present things), I think this "repeated interactivity" might help drop snore off.

**Comment by tlestang** [comment]
Yep, that would be really great. Ideally we would identify "real-life" R that fit each situation. Maybe we could reuse some of the Trachoma code, but I don't know if people would appreciate. Any other idea regarding source of R code we could use as illustrations ? For some of the smells we can probably come with examples ourselves.

**Comment by ben18785** [comment]
Real life would be good but may be tricky to find in time. Not sure, as you say, we should use the Trachoma code to avoid conflicts of interest.

Options would be to look at the Como work and, potentially, some of the Imperial Covid models (I don't think we'd want to report where the chunks came from though, to not embarrass anyone).

As a suggestion, we could create issues for each of these smells and both post examples?

**Comment by tlestang** [comment]
Sounds good. One thing we could do is looking for already existing examples for these smells and adapt them into something relevant to epidemiological models
